name: asnow
base: core18
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: An amazing ASCII waste of time
description: |
  asnow is highly accurate simulation of atmospheric precipitation of ice
  crystals (ordinarily known as "snow"). Snowflakes can have a variety of
  shapes and are represented by ASCII characters, and may melt from time
  to time.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  asnow:
    command: bin/asnow

parts:
  asnow:
    source: .
    plugin: make
    build-packages:
      - gcc
      - make
